spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: true
        secure: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      zone: zone1
      profile: ${spring.profiles.active:default}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Auth Service ITIC Paris
    description: Authentication and User Management Service
    version: 1.0.0
  team: Dev ITIC Paris
  contact:
    email: dev@iticparis.com

logging:
  level:
    com.iticparis.auth: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO

ypareo:
  service:
    base-url: http://localhost:8082
    timeout: 10

resilience4j:
  circuitbreaker:
    instances:
      ypareo-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
  retry:
    instances:
      ypareo-service:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

security:
  bcrypt:
    strength: 12

jwt:
  secret: iticParis2024SecretKeyForStudentAppAuthenticationAndAuthorization
  expiration: 86400000
  refresh-expiration: 604800000
